//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platoons
    {
        public Platoons()
        {
            this.Recruits = new HashSet<Recruits>();
            this.Staff = new HashSet<Staff>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime InitialDate { get; set; }
        public System.DateTime FinalDate { get; set; }
    
        public virtual ICollection<Recruits> Recruits { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
